sudo: false
language: node_js
matrix:
  include:
    - node_js: "12"
    - node_js: "10"
      script:
        - ./node_modules/.bin/grunt && istanbul report text && ( cat coverage/lcov.info | $(npm get prefix)/bin/coveralls || true ) && rm -rf coverage
      before_script:
        - npm install -g istanbul coveralls
    - node_js: "8"
