sudo: false
addons:
  chrome: stable
language: node_js
matrix:
  include:
    - node_js: "14"
      script:
        - ./node_modules/.bin/grunt && ( cat coverage/lcov.info | $(npm get prefix)/bin/coveralls || true ) && rm -rf coverage
        #    - scripts/install-ui-test-dependencies.sh && grunt test-ui
      before_script:
        - npm install -g coveralls
    - node_js: "12"
      script:
        - ./node_modules/.bin/grunt no-coverage
    - node_js: "10"
      script:
        - ./node_modules/.bin/grunt no-coverage
    - node_js: "8"
      script:
        - ./node_modules/.bin/grunt no-coverage
