blank_issues_enabled: true
contact_links:
  - name: â“ Questions
    url: https://discourse.nodered.org
    about: Ask your question on the Node-RED forum
  - name: â­ï¸ Feature Request
    url: https://discourse.nodered.org/c/development/feature-requests
    about: Discuss your request with the community
  - name: ğŸ—‚ Documentation
    url: https://nodered.org/docs
    about: Go straight to the documentation
  - name: ğŸ’¬ Slack
    url: https://nodered.org/slack
    about: Chat about the project on our slack team
