name: Publish Release
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  generate:
    name: 'Update node-red-docker image'
    runs-on: ubuntu-latest
    steps:
      - name: Check out node-red repository
        uses: actions/checkout@v4
        with:
            path: 'node-red'
      - name: Check out node-red-docker repository
        uses: actions/checkout@v4
        with:
            repository: 'node-red/node-red-docker'
            path: 'node-red-docker'
      - name: Check out node-red.github.io repository
        uses: actions/checkout@v4
        with:
            repository: 'node-red/node-red.github.io'
            path: 'node-red.github.io'
      - uses: actions/setup-node@v4
        with:
            node-version: '16'
      - run: node ./node-red/.github/scripts/update-node-red-docker.js
      - name: Create Docker Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.NR_REPO_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          path: 'node-red-docker'
          commit-message: 'Bump to ${{ env.newVersion }}'
          title: 'ðŸš€ Update to Node-RED ${{ env.newVersion }} release'
          body: |
            Updates the Node-RED Docker repo for the ${{ env.newVersion }} release.

            Once this is merged, you will need to create a new release with the tag `v${{ env.newVersion }}`.

            This PR was auto-generated by a GitHub Action. Any questions, speak to @knolleary
      - run: node ./node-red/.github/scripts/update-node-red-website.js
      - name: Create Website Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.NR_REPO_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          path: 'node-red.github.io'
          commit-message: 'Bump to ${{ env.newVersion }}'
          title: 'ðŸš€ Update to Node-RED ${{ env.newVersion }} release'
          body: |
            Updates the Node-RED Website repo for the ${{ env.newVersion }} release.

            This PR was auto-generated by a GitHub Action. Any questions, speak to @knolleary
